name: Update Express Template
on: workflow_dispatch
#on:
  #schedule:
    # 12:00 UTC on the first of the month.
    #- cron:  '0 12 1 * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Download Repository"
        uses: actions/checkout@v2
        with:
            repository: tjohnston-softdev/njs-express-template
            path: repo
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: "Download Template Files"
        run: |
          mkdir -p ./files/njs-express-template
          cd ./files/njs-express-template
          npx express-generator --view=ejs --git
      - name: "Create Placeholder Files"
        run: |
          cd ./files/njs-express-template
          echo "# Images go here" > ./public/images/readme.md
          echo "# Front-end JavaScript files go here." > ./public/javascripts/readme.md
      - name: "Remove Old Files"
        run: |
          cd ./repo
          find . ! -name .git -type d -maxdepth 1 -exec rm -r {} \;
          find . ! -name .gitignore ! -name license.txt ! -name readme.md -type f -maxdepth 1 -exec rm -r {} \;
      - name: "Update Files"
        run: |
          cd ./files/njs-express-template
          cp * ../../repo -R
          ls -a -R ../../repo
      - name: "Save Changes"
        run: |
          cd ./repo
          date > ./update-timestamp.txt
          TODAY_DATE=$(date +"%Y-%m-%d")
          TAG_NAME=$(echo "devops3")
          TSTAMP=$(date)
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "DevOps ($TSTAMP)"
          git push origin master
          SHORT_HASH=$(git rev-parse HEAD)
          echo "today=$TODAY_DATE" >> $GITHUB_ENV
          echo "tag=$TAG_NAME" >> $GITHUB_ENV
          echo "comhash=$SHORT_HASH" >> $GITHUB_ENV
      - name: "Create Release"
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: DevOps Test Release
          tag_name: ${{ env.tag }}
          body: Express server template - DevOps - (${{ env.today }})
          owner: tjohnston-softdev
          repo: njs-express-template
          commitsh: ${{ env.comhash }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
